# Worksheet 04

Name:  Hao Qi  
UID:  U96305250  

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the Minkowski Distance, describe what the parameters p and d are.

- **p** determines the type of distance calculation. For p=1, it yields the Manhattan distance; for p=2, it yields the Euclidean distance; and for the other values of p, it defines different forms of distance between points in a vector space. 
- **d** represents the dimensionality of data points (i.e., the number of features) to be compared. It refers to the number of coordinates in a vector space. The calculation of the Minkowski distance involves summing up the absolute differences raised to the power of p across all these dimensions and taking the root. 

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean measures the shortest straight-line distance between two points. It is calculated at p=2 by taking the root of the sum of the squared differences between corresponding coordinates. On the other hand, Manhattan calculates the distance at p=1 by summing up the absolute values of the differences, assuming one can only move along the orthogonal paths on a map. 

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think the distance would look like when p is very large.

The distance is getting smaller and approaching the maximum absolute difference along any coordinate dimension, which is 1 here. 

d) Is the Minkowski Distance still a distance function when p < 1? Expain why / why not.

No. Because the function no longer satisfies the triangle inequality, which is one of the necessary conditions for it to be considered a distance. There is an example on the slides from Page 29 to Page 33. 

e) When would you use the Cosine Similarity over the Euclidean Distance?

It is preferred when the orientation of data points is more important than their magnitude or absolute positions. This is particularly relevant in contexts like text analysis or information retrieval, where the similarity between documents or vectors is based on their angle instead of their length. 

f) What does the Jaccard Distance account for that the Manhattan Distance doesn't?

Jaccard measures how similar two sets are based on the overlap of their intersection and union, while Manhattan sums the absolute differences between points. As a result, Jaccard helps alleviate the interference of set size in measuring differences with elements and helps compare the similarity between sets, such as documents, where the focus is on the presence or absence of features rather than their magnitude. 

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

Using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'name', 'is', 'Alice', 'Bob', 'my']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [4]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [5]:
new_all_words = list(set([item for x in corpus for item in x.split()]))  # new union
print(new_all_words) 

['hello', 'name', 'is', 'Alice', 'Bob', 'Claude', 'my', 'hi']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [6]:
new_v1 = [1 if x in s1 else 0 for x in new_all_words]
new_v2 = [1 if x in s2 else 0 for x in new_all_words]
new_v3 = [1 if x in s3 else 0 for x in new_all_words]
print(new_v1)
print(new_v2)
print(new_v3)

[1, 1, 1, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 1, 0]
[0, 1, 1, 0, 0, 1, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [8]:
def minkowski(x, y, p):
    if len(x) != len(y):
        raise RuntimeError("x and y should have the same dimension!")
    
    res = 0
    for i in range(len(x)):
        res += abs(x[i] - y[i]) ** p
    return res ** (1 / p)

def manhattan(x, y):
    return minkowski(x, y, 1)


vectors = [new_v1, new_v2, new_v3]
similar_pair = None
min_distance = float('inf')

for i in range(len(vectors)):
    for j in range(i+1, len(vectors)):
        distance = manhattan(vectors[i], vectors[j])
        print("vec{} and vec{}: {}".format(i+1, j+1, distance))
        if distance < min_distance:
            min_distance = distance
            similar_pair = (i+1, j+1)

print("{} has the smallest distance, which is {}. ".format(similar_pair, min_distance))

vec1 and vec2: 2.0
vec1 and vec3: 4.0
vec2 and vec3: 4.0
(1, 2) has the smallest distance, which is 2.0. 


Vector 1 and Vector 2 are the most similar under the manhattan distance. 

d) Create a matrix of all these vectors (row-major) and add the following sentences:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [11]:
matrix = [new_v1, new_v2, new_v3]

new_corpus = ["hi Alice", 
          "hello Claude", 
          "Bob my name is Claude", 
          "hi Claude my name is Alice", 
          "hello Bob"]
for i in range(len(new_corpus)):
    new_vec = [1 if x in new_corpus[i] else 0 for x in new_all_words]
    matrix.append(new_vec)

for i in range(len(matrix)):
    print(matrix[i])

[1, 1, 1, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 1, 0]
[0, 1, 1, 0, 0, 1, 1, 1]
[0, 0, 0, 1, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 1, 0, 0]
[0, 1, 1, 0, 1, 1, 1, 0]
[0, 1, 1, 1, 0, 1, 1, 1]
[1, 0, 0, 0, 1, 0, 0, 0]


e) How many rows and columns does this matrix have?

In [12]:
print("The matrix has {} rows and {} columns. ".format(len(matrix), len(matrix[0])))

The matrix has 8 rows and 8 columns. 


f) When using the Manhattan distance, which two sentences are the most similar?

In [14]:
similar_pair = None
min_distance = float('inf')

for i in range(len(matrix)):
    for j in range(i+1, len(matrix)):
        distance = manhattan(matrix[i], matrix[j])
        print("sentence{} and sentence{}: {}".format(i+1, j+1, distance))
        if distance < min_distance:
            min_distance = distance
            similar_pair = (i+1, j+1)

print("Sentence {0[0]} and Sentence {0[1]} are the most similar with a distance of {1}. ".format(similar_pair, min_distance))

sentence1 and sentence2: 2.0
sentence1 and sentence3: 4.0
sentence1 and sentence4: 5.0
sentence1 and sentence5: 5.0
sentence1 and sentence6: 4.0
sentence1 and sentence7: 3.0
sentence1 and sentence8: 5.0
sentence2 and sentence3: 4.0
sentence2 and sentence4: 7.0
sentence2 and sentence5: 5.0
sentence2 and sentence6: 2.0
sentence2 and sentence7: 5.0
sentence2 and sentence8: 3.0
sentence3 and sentence4: 5.0
sentence3 and sentence5: 5.0
sentence3 and sentence6: 2.0
sentence3 and sentence7: 1.0
sentence3 and sentence8: 7.0
sentence4 and sentence5: 4.0
sentence4 and sentence6: 7.0
sentence4 and sentence7: 4.0
sentence4 and sentence8: 4.0
sentence5 and sentence6: 5.0
sentence5 and sentence7: 6.0
sentence5 and sentence8: 2.0
sentence6 and sentence7: 3.0
sentence6 and sentence8: 5.0
sentence7 and sentence8: 8.0
Sentence 3 and Sentence 7 are the most similar with a distance of 1.0. 


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [3]:
import numpy as np 

# Calculate customized pairwise distances between graphs. 
# Input: 
#   a list of 2D adjacency matrices
# Output:
#   a pairwise distance matrix
def dis(adjacency_matrices):
    n = len(adjacency_matrices)
    res = np.full((n,n), -1)

    for i in range(n):
        for j in range(n):
            mat_i = adjacency_matrices[i]
            mat_j = adjacency_matrices[j]
            res[i][j] = np.sum(np.abs(mat_i - mat_j)) / 2

    return res

# Test (assuming they are undirected and unweighted graphs)
m1 = np.array([[0, 1, 1], [1, 0, 0], [1, 0, 0]])
m2 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
m3 = np.array([[0, 0, 1], [0, 0, 1], [1, 1, 0]])
print("graph 1: \n", m1)
print("graph 2: \n", m2)
print("graph 3: \n", m3)
print("dis: \n", dis([m1, m2, m3]))


graph 1: 
 [[0 1 1]
 [1 0 0]
 [1 0 0]]
graph 2: 
 [[0 1 0]
 [1 0 1]
 [0 1 0]]
graph 3: 
 [[0 0 1]
 [0 0 1]
 [1 1 0]]
dis: 
 [[0 2 2]
 [2 0 2]
 [2 2 0]]
